
FROM node:20-alpine
WORKDIR /app

# Contexto agora é ./backend
COPY package*.json ./

# Adiciona docker-cli e docker-compose (standalone) para orquestração
# Adiciona openssl e certbot para gestão de SSL
RUN apk add --no-cache certbot openssl docker-cli docker-compose
RUN npm install

# Copia arquivos do backend
COPY . .

RUN npm run build
EXPOSE 3000
CMD ["node", "dist/server.js"]
