
FROM node:20-alpine
WORKDIR /app

# Contexto agora é ./backend
COPY package*.json ./

RUN apk add --no-cache certbot openssl
RUN npm install

# Copia arquivos do backend
COPY . .

RUN npm run build
EXPOSE 3000
CMD ["node", "dist/server.js"]
