
FROM node:20-alpine
WORKDIR /app

# Contexto agora é ./backend
COPY package*.json ./

# Adiciona docker-cli para permitir reload do nginx e openssl/certbot para SSL
RUN apk add --no-cache certbot openssl docker-cli
RUN npm install

# Copia arquivos do backend
COPY . .

RUN npm run build
EXPOSE 3000
CMD ["node", "dist/server.js"]
